# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9825be3ee28e75663a597df295c062e91829521cac685e38185a26b7c5399f9d49ac6832127aa0b44a385eba06fa3864abfbcb7e49dfd50876c9c52b8326a3fd

test:
  secret_key_base: cb22eb9d68abf62f661916513b8cb461ed1906418e4a7be5ba9edc5fc601748f70e5873e27294318cfadd8a7e0a8b80643f41a31527959ed05ac080fc9e2d651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
